MenuText::
    db "1 WARRIOR 1+2   "
    db "2 WARRIOR 3     "
    db "3 RESDEN EVIL   "
    db "4 CANNON FODDER "
    db "5 METAL GEAR SOL"
    db "6 ZELDA AGES    "
    db "7 ZELDA AWAKENIN"
    db "8 ZELDA SEASONS "
    db "9 BIONIC COMMAND"
    db "10 BOMBERMAN QUE"
    db "11 R-TYPE DX    "
    db "12 SURVIVAL KIDS"
    db "13 SPY VS SPY   "
    db "14 THE SIMPSONS "
    db "15 ADVEN ISLAND1"
    db "16 ADVEN ISLAND2"
    db "17 SUPER CONTRA1"
    db "18 SUPER CONTRA2"
    db "19 ARMY MEN 3   "

BottomText::
    db " DRAGON WARRIOR 1 2 "
    db "  DRAGON WARRIOR 3  "
    db "    RESDEN EVIL     "
    db "    CANNON FODDER   "
    db "  METAL GEAR SOLID  "
    db "ZELDA ORACLE OF AGES"
    db "ZELDA LINK AWAKENING"
    db "ZELDA ORACLE OF SEAS"
    db "BIONIC COMMANDO FORC"
    db "  BOMBERMAN QUEST   "
    db "     RTYPE DX       "
    db "   SURVIVAL KIDS    "
    db "    SPY VS SPY      "
    db "THE SIMPSONS NIGHT O"
    db " ADVENTURE ISLAND I "
    db "ADVENTURE ISLAND II "
    db "   SUPER CONTRA 1   "
    db "   SUPER CONTRA 2   "
