MenuText::
    db "1 SUPER MARIO 1 "
    db "2 SUPER MARIO 2 "
    db "3 WARIO LAND 1  "
    db "4 SUPER MARIO DX"
    db "5 WARIO LAND 2  "
    db "6 WARIO LAND 3  "
    db "7 MARIO GOLF    "
    db "8 MARIO TENNIS  "
    db "9 MEGAMAN       "
    db "10 MEGAMAN II   "
    db "11 MEGAMAN III  "
    db "12 ADVENTURE I  "
    db "13 ADVENTURE II "
    db "14 CONTRA 1     "
    db "15 CONTRA 2     "
    db "16 CASTLEVANIA 1"
    db "17 CASTLEVANIA 2"
    db "18 CASTLEVANIA 3"
    db "19 SPUD'S ADVENT"
    db "20 SUPER BOMBLIS"
    db "21 PRINCE OF PER"
    db "22 ALFRED CHICKE"
    db "23 BATMAN       "
    db "24 TETRIS BLAST "
    db "25 ROBOCOP      "
    db "26 BLUES BROTHER"
    db "27 FLASH, THE   "
    db "28 SPIDERMAN XME"
    db "29 PANG         "
    db "30 TOM & JERRY  "
    db "31 FIRE FIGHTER "
    db "32 ULTRAMAN     "
    db "33 PITMAN       "
    db "34 DR. MARIO    "
    db "35 PALAMEDES    "
    db "36 BOMB JACK    "
    db "37 JIMMY CONNORS"
    db "38 PAC-MAN      "
    db "39 SNOOPY - MAGI"
    db "40 HEAVYWEIGHT C"
    db "41 MALIBU BEACH "
    db "42 SOLOMON'S CLU"
    db "43 WIZARDS & WAR"
    db "44 YOSHI        "
    db "45 SOLAR STRIKER"
    db "46 HATRIS       "
    db "47 PANEL ACTION "
    db "48 BURAI FIGHTER"
    db "49 HOME ALONE   "
    db "50 Q BILLION    "
    db "51 MONSTER TRUCK"
    db "52 MANCINE PLUS "
    db "53 PAPERBOY     "
    db "54 MONSTER RACE "
    db "55 DEXTERITY    "
    db "56 SUPER BOMBLIS"
    db "57 SUPER GOGO TA"
    db "58 TAIL 'GATOR  "
    db "59 POWER RACER  "
    db "60 CHINESE HERO "
    db "61 WARRIOR      "

BottomText::
    db " SUPER MARIO LAND 1 "
    db " SUPER MARIO LAND 2 "
    db "WARIO LAND 1 SUPER M"
    db "SUPER MARIO BROS  DX"
    db "    WARIO LAND 2    "
    db "    WARIO LAND 3    "
    db "    MARIO GOLF      "
    db "    MARIO TENNIS    "
    db "    MEGA MAN        "
    db "    MEGA MAN II     "
    db "    MEGA MAN III    "
    db " ADVENTURE ISLAND I "
    db "ADVENTURE ISLAND II "
    db "  SUPER CONTRA 1    "
    db "  SUPER CONTRA 2    "
    db "CASTLEVANIA - LEGEND"
    db "CASTLEVANIA II - BEL"
    db "  CASTLEVANIA 3     "
    db " SPUD'S ADVENTURE   "
    db "   SUPER BOMBLISS   "
    db "  PRINCE OF PERSIA  "
    db "  ALFRED CHICKEN    "
    db "BATMAN - THE ANIMATE"
    db "   TETRIS BLAST     "
    db "      ROBOCOP       "
    db "BLUES BROTHERS, THE "
    db "    FLASH, THE      "
    db "SPIDER-MAN AND THE X"
    db "       PANG         "
    db "   TOM AND JERRY    "
    db "    FIRE FIGHTER    "
    db "     ULTRAMAN       "
    db "      PITMAN        "
    db "     DR. MARIO      "
    db "     PALAMEDES      "
    db "     BOMB JACK      "
    db "JIMMY CONNORS TENNIS"
    db "     PAC-MAN        "
    db "SNOOPY - MAGIC SHOW "
    db "HEAVYWEIGHT CHAMPION"
    db "MALIBU BEACH VOLLEYB"
    db "  SOLOMON'S CLUB    "
    db "WIZARDS AND WARRIORS"
    db "    YOSHI           "
    db "   SOLAR STRIKER    "
    db "      HATRIS        "
    db " PANEL ACTION BINGO "
    db "BURAI FIGHTER DELUXE"
    db "    HOME ALONE      "
    db "    Q BILLION       "
    db "   MONSTER TRUCK    "
    db "   MANCINE PLUS     "
    db "     PAPERBOY       "
    db "   MONSTER RACE     "
    db "    DEXTERITY       "
    db "   SUPER BOMBLISS   "
    db "   SUPER GOGO TANK  "
    db "    TAIL GATOR      "
    db "    POWER RACER     "
    db "    CHINESE HERO    "
    db "      WARRIOR       "
