
MenuText::
    db "1 POKEMON GOLDEN"
    db "2 POKEMON SLIVER"
    db "3 POKEMON CRYSTA"
    db "4 FIGHTER 1999  "
    db "5 HAVERST MOON 2"
    db "6 POKEMON YELLOW"
    db "7 POKEMON BLUE  "
    db "8 POKEMON GREEN "
    db "9 POKEMON RED   "
    db "10 HAVERST MOON4"
    db "11 HAVERST MOON3"
    db "12 REAL KOEI SAN"
    db "13 SUPER MAIRODX"
    db "14 METAL GEAR   "
    db "15 POKEMON MONST"
    db "16 THE WAR OF VI"
    db "17 KOF 1996     "
    db "18 KOF 1995     "
    db "19 GHOSTBUSTERS "
    db "20 SNOW BROS    "
    db "21 TURRICAN     "
    db "22 CONTRA       "
    db "23 PITMA        "
    db "24 DR. MARIO    "
    db "25 PALAMEDES    "
    db "26 RENJU CLUB   "
    db "27 BOMB JACK    "
    db "28 JIMMY CONNORS"
    db "29 PAC MAN      "
    db "30 PUZZLE BOY II"
    db "31 SNOOPY MAGIC "
    db "32 CHAMP BOXING "
    db "33 MALIBU BEACH "
    db "34 RACING TAMASH"
    db "35 SOLOMONS CLUB"
    db "36 ZOIDS DENSETS"
    db "37 WIZARDS & WAR"
    db "38 SUPER YOSHI  "
    db "39 SOLAR STRIKER"
    db "40 HATRIS       "
    db "41 PANEL ACTION "
    db "42 BURAI FIGHTER"
    db "43 HOME ALONE   "
    db "44 Q BILLION    "
    db "45 MONSTER TRUCK"
    db "46 MANCINE PLUS "
    db "47 SA GA 3 JIKUU"
    db "48 PAPERBOY     "
    db "49 NBA SUPER STA"
    db "50 MONSTER RACE "
    db "51 DEXTERITY    "
    db "52 SUPER BOMBLIS"
    db "53 SUPER GOGO TA"
    db "54 TAIL    GATOR"
    db "55 CASTLEVANIA 3"
    db "56 POWER RACER  "
    db "57 CHINESE HERO "
    db "58 NAILN SCALE  "
    db "59 ROLANS CURSE "
    db "60 SUPER MARIO L"
    db "61 SAIN WORLD   "
    db "62 PINBALL 66HIK"
    db "63 WARRIOR      "
    db "64 PENGUIN KUN W"
    db "65 F 15 STRIKE E"
    db "66 CHAMPIONSHIP "
    db "67 SNOOPY NO HAJ"
    db "68 ADVENTURES OF"
    db "69 SKATE OR DIE "
    db "70 ATOMIC PUNK  "
    db "71 BATMAN RETURN"
    db "72 PUNISHER, THE"
    db "73 ALIEN 3      "
    db "74 CASPER       "
    db "75 STAR TREK GEN"
    db "76 TEKE! TEKE! A"
    db "77 WWF SUPERSTAR"
    db "78 INDIANA JONES"
    db "79 POPN TWINBEE "
    db "80 DEAD HEAT SCR"
    db "81 BUST A MOVE 2"
    db "82 MOMOTAROU COL"
    db "83 FLINTSTONES, "
    db "84 SUPER DUCK   "
    db "85 F1 HERO GB   "
    db "86 DOUBLE DRAGON"
    db "87 LITTLE INDIAN"
    db "88 DOUBLE DRAGON"
    db "89 SHADOW WARRIO"
    db "90 3D ALIEN ADVE"
    db "91 ADVENTURE ISL"
    db "92 ROB MAN      "
    db "93 SUPER BOMBLIS"
    db "94 PRINCE OF PER"
    db "95 ALFRED CHICKE"
    db "96 BATMAN THE AN"
    db "97 TETRIS BLAST "
    db "98 ROBOCOP      "
    db "99 BLUES BROTHER"
    db "100 FLASH, THE  "
    db "101 NONTAN TO IS"
    db "102 SPIDER MAN A"
    db "103 BASEBALL    "
    db "104 PANG        "
    db "105 TOM AND JERR"
    db "106 SPEEDBALL 2 "
    db "107 FIRE FIGHTER"
    db "108 ULTRAMAN    "

BottomText::
