MenuText::
    db "1 POKEMON YELLOW"
    db "2 POKEMON GOLD  "
    db "3 POKEMON BLUE  "
    db "4 POKEMON SILVER"
    db "5 POKEMON CRYSTA"
    db "6 POKEMON PINBAL"
    db "7 POKEMON RED   "
    db "8 POKEMON CARD  "
    db "9 POKEMON PUZZLE"
    db "10 RESIDENT EVIL"
    db "11 MEGA MAN X1  "
    db "12 MEGA MAN X2  "
    db "13 HARVEST MOON1"
    db "14 HARVEST MOON2"
    db "15 HARVEST MOON3"
    db "16 EVIL KNIEVEL "
    db "17 GHOSTS N GOBL"
    db "18 MORTAL KOMBAT"
    db "19 KONAMI VOL 3 "
    db "20 KONAMI VOL 4 "
    db "21 EARTHWORM JIM"
    db "22 EXTREME GHOST"

BottomText::
    db "   POKEMON YELLOW   "
    db "    POKEMON GOLD    "
    db "    POKEMON BLUE    "
    db "   POKEMON SILVER   "
    db "   POKEMON CRYSTAL  "
    db "   POKEMON PINBALL  "
    db "    POKEMON RED     "
    db "POKEMON TRADING CARD"
    db "POKEMON PUZZLE CHALL"
    db "RESIDENT EVIL GAIDEN"
    db " MEGA MAN  XTREME 1 "
    db " MEGA MAN  XTREME 2 "
    db "   HARVEST MOON 1   "
    db "   HARVEST MOON 2   "
    db "   HARVEST MOON 3   "
    db "   EVIL KNIEVEL     "
    db "  GHOSTS N GOBLINS  "
    db "  MORTAL KOMBAT 4   "
    db "KONAMI COLLECTION 3 "
    db "KONAMI COLLECTION 4 "
    db "   EARTHWORM JIM    "
    db "EXTREME GHOSTBUSTERS"
