MenuText::
    db "1 SHANTAE       "
    db "2 PERFECT DARK  "
    db "3 DONKEY KONG CO"
    db "4 STAR OCEAN    "
    db "5 DUKE NUKEM    "
    db "6 MARIO BROS DEL"
    db "7 WARIO LAND 2  "
    db "8 WARIO LAND 3  "
    db "9 MARIO GOLF    "
    db "10 MARIO TENNIS "
    db "11 GAME WATCH G2"
    db "12 GAME WATCH G3"
    db "13 MEGAMAN      "
    db "14 MEGAMAN II   "
    db "15 MEGAMAN III  "
    db "16 CASTLEVANIA  "
    db "17 HANDS OF TIME"
    db "18 RETURN OF THE"
    db "19 CASTLEVANIA 2"
    db "20 SPUDS ADVENTU"

BottomText::
    db "       SHANTAE      "
    db "    PERFECT DARK    "
    db "DONKEY KONG COUNTRY "
    db "STAR OCEAN BLUESPHER"
    db "     DUKE NUKEM     "
    db " MARIO BROS DELUXE  "
    db "   WARIO LAND 2     "
    db "   WARIO LAND 3     "
    db "    MARIO GOLF      "
    db "    MARIO TENNIS    "
    db "GAME WATCH GALLERY 2"
    db "GAME WATCH GALLERY 3"
    db "      MEGAMAN I     "
    db "     MEGAMAN II     "
    db "     MEGAMAN III    "
    db " CASTLEVANIA LEGENDS"
    db "   HANDS OF TIME    "
    db "RETURN OF THE NINJA "
    db "   CASTLEVANIA 2    "
    db "  SPUDS  ADVENTURE  "
