MenuText::
    db "1 POKEMON YELLOW"
    db "2 POKEMON GOLD  "
    db "3 POKEMON BLUE  "
    db "4 POKEMON SILVER"
    db "5 POKEMON CRYSTA"
    db "6 POKEMON RED   "
    db "7 POKEMON TRADIN"
    db "8 POKEMON PUZZLE"
    db "9 RESIDENT EVIL "
    db "10 MEGA MAN  X1 "
    db "11 MEGA MAN  X2 "
    db "12 HARVEST MOON1"
    db "13 HARVEST MOON2"
    db "14 HARVEST MOON3"
    db "15 MEGAMAN II   "
    db "16 MEGAMAN III  "
    db "17 KOF 1996     "
    db "18 KOF 1995     "
    db "19 REAL GHOSTBUS"
    db "20 SNOW BROS. JR"
    db "21 TURRICAN (UE)"
    db "22 CONTRA       "
    db "23 PITMAN       "
    db "24 DR. MARIO    "
    db "25 PALAMEDES    "
    db "26 RENJU CLUB   "
    db "27 BOMB JACK    "
    db "28 JIMMY CONNORS"
    db "29 PAC-MAN      "
    db "30 PUZZLE BOY II"
    db "31 SNOOPY MAGIC "
    db "32 HEAVYWEIGHT C"
    db "33 MALIBU BEACH "
    db "34 RACING TAMASH"
    db "35 SOLOMON'S CLU"
    db "36 ZOIDS DENSETS"
    db "37 1203.WIZARDS "
    db "38 YOSHI        "
    db "39 SOLAR STRIKER"
    db "40 HATRIS       "
    db "41 PANEL ACTION "
    db "42 BURAI FIGHTER"
    db "43 I SHI DO     "
    db "44 DEAD HEAT SCR"
    db "45 MOUSE TRAP HO"
    db "46 BIONIC BATTLE"
    db "47 SA-GA 3 JIKUU"
    db "48 PAPERBOY     "
    db "49 SUPER STAR   "
    db "50 MR. CHIN'S GO"
    db "51 DEXTERITY    "
    db "52 ASMIK WORLD  "
    db "53 SUPER GOGO TA"
    db "54 TAIKYOKU RENJ"
    db "55 CASTLEVANIA 3"
    db "56 POWER RACER  "
    db "57 ROLAN'S CURSE"
    db "58 ZOOP         "
    db "59 NAIL'N SCALE "
    db "60 SUPER MARIO  "
    db "61 PARASOL HENBE"
    db "62 PINBALL 66HIK"
    db "63 WARRIOR      "
    db "64 PENGUIN-KUN W"
    db "65 F-15 STRIKE E"
    db "66 CHAMPIONSHIP "
    db "67 SNOOPY NO HAJ"
    db "68 ADVENTURES OF"
    db "69 SKATE OR DIE "
    db "70 ATOMIC PUNK  "
    db "71 BATMAN RETURN"
    db "72 PUNISHER, THE"
    db "73 ALIEN 3      "
    db "74 CASPER       "
    db "75 STAR TREK GEN"
    db "76 TEKE  TEKE  A"
    db "77 WWF SUPERSTAR"
    db "78 INDIANA JONES"
    db "79 POP N TWINBEE"
    db "80 LAST ACTION H"
    db "81 BUST-A-MOVE 2"
    db "82 TOWER OF DRUA"
    db "83 FLINTSTONES, "
    db "84 SUPER DUCK   "
    db "85 F1 HERO GB   "
    db "86 DOUBLE DRAGON"
    db "87 LITTLE INDIAN"
    db "88 DOUBLE DRAGON"
    db "89 SHADOW WARRIO"
    db "90 ALTERED SPACE"
    db "91 ADVENTURE ISL"
    db "92 KIDOUKEISATSU"
    db "93 SUPER BOMBLIS"
    db "94 PRINCE OF PER"
    db "95 ALFRED CHICKE"
    db "96 BATMAN THE AN"
    db "97 TETRIS BLAST "
    db "98 ROBOCOP      "
    db "99 BLUES BROTHER"
    db "100 FLASH, THE  "
    db "101 NONTAN TO IS"
    db "102 SPIDER-MAN A"
    db "103 BALLOON KID "
    db "104 PANG        "
    db "105 TOM JERRY   "
    db "106 SPEEDBALL 2 "
    db "107 FIRE FIGHTER"
    db "108 ULTRAMAN    "

BottomText::
    db "   POKEMON YELLOW   "
    db "   POKEMON GOLD     "
    db "   POKEMON BLUE     "
    db "   POKEMON SILVER   "
    db "  POKEMON CRYSTAL   "
    db "   POKEMON RED      "
    db "POKEMON TRADING CARD"
    db "POKEMON PUZZLE CHALL"
    db "RESIDENT EVIL GAIDEN"
    db "   MEGA MAN X1      "
    db "   MEGA MAN X2      "
    db "   HARVEST MOON 1   "
    db "   HARVEST MOON 2   "
    db "   HARVEST MOON 3   "
    db "   MEGAMAN II       "
    db "   MEGAMAN III      "
    db "     KOF 1996       "
    db "     KOF 1995       "
    db "REAL GHOSTBUSTERS TH"
    db "   SNOW BROS. JR.   "
    db "     TURRICAN       "
    db "     CONTRA         "
    db "     PITMAN         "
    db "     DR. MARIO      "
    db "    PALAMEDES       "
    db "    RENJU CLUB      "
    db "     BOMB JACK      "
    db "JIMMY CONNORS TENNIS"
    db "     PAC-MAN        "
    db "   PUZZLE BOY II    "
    db " SNOOPY MAGIC SHOW  "
    db "HEAVYWEIGHT CHAMPION"
    db "MALIBU BEACH VOLLEYB"
    db "   RACING TAMASHII  "
    db "   SOLOMONS CLUB    "
    db "  ZOIDS DENSETSU    "
    db "   WIZARDS WARRIOR  "
    db "     YOSHI          "
    db "   SOLAR STRIKER    "
    db "     HATRIS         "
    db "  PANEL ACTION BINGO"
    db "BURAI FIGHTER DELUXE"
    db "    I SHI DO        "
    db " DEAD HEAT SCRAMBLE "
    db "   MOUSE TRAP HOTEL "
    db "   BIONIC BATTLER   "
    db "       CYRAID       "
    db "    PAPERBOY        "
    db "    SUPER STAR      "
    db "MR. CHIN'S GOURMET P"
    db "    DEXTERITY       "
    db "  TEKE! ASMIK WORLD "
    db "  SUPER GOGO TANK   "
    db "  TAIKYOKU RENJU    "
    db "   CASTLEVANIA 3    "
    db "    POWER RACER     "
    db "   ROLAN'S CURSE    "
    db "        ZOOP        "
    db "    NAIL'N SCALE    "
    db "SUPER MARIO LAND    "
    db "  PARASOL HENBEE    "
    db "PINBALL 66HIKI NO WA"
    db "     WARRIOR        "
    db "PENGUIN-KUN WARS VS."
    db "  F-15 STRIKE EAGLE "
    db "  CHAMPIONSHIP POOL "
    db "SNOOPY NO HAJIMETE N"
    db "ADVENTURES OF STAR S"
    db "SKATE OR DIE TOUR DE"
    db "    ATOMIC PUNK     "
    db "BATMAN RETURN OF THE"
    db "PUNISHER THE THE ULT"
    db "     ALIEN 3        "
    db "      CASPER        "
    db "STAR TREK GENERATION"
    db "TEKE! TEKE! ASMIK WO"
    db "  WWF SUPERSTARS 2  "
    db "INDIANA JONES AND TH"
    db "   POPN TWINBEE     "
    db "  LAST ACTION HERO  "
    db "BUST-A-MOVE 2 ARCADE"
    db "TOWER OF DRUAGA, THE"
    db "FLINTSTONES THE KING"
    db "    SUPER DUCK      "
    db "    F1 HERO GB      "
    db "  DOUBLE DRAGON II  "
    db "LITTLE INDIAN IN BIG"
    db "  DOUBLE DRAGON     "
    db " SHADOW WARRIORS    "
    db "   ALTERED SPACE    "
    db "  ADVENTURE ISLAND  "
    db "KIDOUKEISATSU PATLAB"
    db "  SUPER BOMBLISS    "
    db "  PRINCE OF PERSIA  "
    db "  ALFRED CHICKEN    "
    db "BATMAN THE ANIMATED "
    db "   TETRIS BLAST     "
    db "     ROBOCOP        "
    db "BLUES BROTHERS THE J"
    db "     FLASH THE      "
    db "NONTAN TO ISSHO KURU"
    db "SPIDER-MAN AND THE X"
    db "    BALLOON KID     "
    db "      PANG          "
    db "     TOM JERRY      "
    db "SPEEDBALL 2 BRUTAL D"
    db "     FIRE FIGHTER   "
    db "     ULTRAMAN       "
