MenuText::
    db "1 TOMB RAIDER 2 "
    db "2 TOMB RAIDER 1 "
    db "3 CONKER POCKET "
    db "4 DRAGON BALL Z "
    db "5 LOONEY TUNES 1"
    db "6 LOONEY TUNES 2"
    db "7 POKEMON DIAMON"
    db "8 TETRIS DX     "
    db "9 DAIKATANA     "
    db "10 MAGI NATION  "
    db "11 LEGO ISLAND 2"
    db "12 SWIV         "
    db "13 ACTION MAN   "
    db "14 CROC2        "
    db "15 THE FRONT OF "
    db "16 WORLD DESTRUC"
    db "17 THUNDERBIRDS "
    db "18 ARMY MEN 2   "
    db "19 ARMY MEN 3   "

BottomText::
    db "TOMB RAIDER CURSE OF"
    db "    TOMB RAIDER     "
    db "CONKER  POCKET TALES"
    db "DRAGON BALLZ WARRIOR"
    db "LOONEY TUNES COLLECT"
    db "LOONEY TUNES MARVIN "
    db "   POKEMON DIAMOND  "
    db "     TETRIS DX      "
    db "     DAIKATANA      "
    db "     MAGI NATION    "
    db "LEGO ISLAND 2 REVENG"
    db "      SWIV          "
    db "     ACTION MAN     "
    db "      CROC2         "
    db " THE FRONT OF LINE  "
    db " WORLD THUNDER TANK "
    db "    THUNDERBIRDS    "
    db "  ARMY MEN HEROES2  "
    db "ARMY MEN AIR COMBAT "
